my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('login/', views.login),
    path('logout/', views.logout),
    path('home/', views.home),
    path('addresses/', views.address_list, name='address_list'),
    path('addresses/create/', views.address_create, name='address_create'),
    path('addresses/<int:id>/update/', views.address_update, name='address_update'),
    path('addresses/<int:id>/destroy/', views.address_destroy, name='address_destroy'),
]

my_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# CRUD - Create Retrieve Update Delete
STATES_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins'),
)


class Address(models.Model):
    address = models.CharField(max_length=255)
    address_complement = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255, choices=STATES_CHOICES)
    country = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Addresses'

    @property
    def address_complement_normalized(self):
        return '' if self.address_complement is None else self.address_complement

    def __str__(self):
        return '%s, %s, %s' % (self.address, self.city, self.country)

my_app/forms.py
from django import forms
from .models import STATES_CHOICES, Address


# class AddressForm(forms.Form):
#     address = forms.CharField(
#         max_length=255,
#         widget=forms.TextInput(attrs={'class': 'form-control'})
#     )
#     address_complement = forms.CharField(
#         max_length=255,
#         required=False,
#         widget=forms.TextInput(attrs={'class': 'form-control'})
#     )
#     city = forms.CharField(
#         max_length=255,
#         widget=forms.TextInput(attrs={'class': 'form-control'})
#     )
#     state = forms.ChoiceField(
#         choices=STATES_CHOICES,
#         widget=forms.Select(attrs={'class': 'form-control'})
#     )
#     country = forms.CharField(
#         max_length=255,
#         widget=forms.TextInput(attrs={'class': 'form-control'})
#     )

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        # fields = '__all__'
        # fields = ('address','address_complement')
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'address_complement': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'})
        }
        fields = ('address', 'address_complement', 'city', 'state', 'country')

my_app/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from .models import Address, STATES_CHOICES
from .forms import AddressForm


# Create your views here.
def login(request: HttpRequest):
    if request.method == 'GET':
        return render(request, 'my_app/login.html')

    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)

    if user:
        django_login(request, user)
        # next_param = request.GET.get('next')
        # if next_param
        # return HttpResponseRedirect('/home/')
        return redirect('/home/')
    message = 'Credenciais inválidas'
    return render(request, 'my_app/login.html', {'message': message})

    # if request.user.is_authenticated():
    #     request.user.first_name
    #     #logica quando o usuario está autenticado


@login_required(login_url='/login')
def logout(request):
    django_logout(request)
    return redirect('/login/')


@login_required(login_url='/login')
def home(request):
    return render(request, 'my_app/home.html')


@login_required(login_url='/login')
def address_list(request):
    addresses = Address.objects.all()
    # print(list(addresses))
    return render(request, 'my_app/address/list.html', {'addresses': addresses})


@login_required(login_url='/login')
def address_create(request):
    form_submitted = False
    if request.method == 'GET':
        # states = STATES_CHOICES
        form = AddressForm()
    else:
        form_submitted = True
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            # Address.objects.create(
            #     address=form.cleaned_data['address'],
            #     address_complement=form.cleaned_data['address_complement'],
            #     city=form.cleaned_data['city'],
            #     state=form.cleaned_data['state'],
            #     country=form.cleaned_data['country'],
            #     user=request.user
            # )
            return redirect(reverse('my_app:address_list'))

    return render(request, 'my_app/address/create.html', {'form': form, 'form_submitted': form_submitted})


@login_required(login_url='/login')
def address_update(request, id):
    form_submitted = False
    address = Address.objects.get(id=id)
    if request.method == 'GET':
        # states = STATES_CHOICES
        # form = AddressForm(address.__dict__)
        form = AddressForm(instance=address)
    else:
        form_submitted = True
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            # address.address = request.POST.get('address')
            # address.address_complement = request.POST.get('address_complement')
            # address.city = request.POST.get('address_complement')
            # address.state = request.POST.get('state')
            # address.country = request.POST.get('address_complement')
            # address.user = request.user

            # address.save()
            return redirect(reverse('my_app:address_list'))

    return render(request, 'my_app/address/update.html',
                  {'address': address, 'form': form, 'form_submitted': form_submitted})


@login_required(login_url='/login')
def address_destroy(request, id):
    address = Address.objects.get(id=id)
    if request.method == 'GET':
        form = AddressForm(instance=address)
    else:
        address.delete()
        return redirect(reverse('my_app:address_list'))

    return render(request, 'my_app/address/destroy.html', {'address': address, 'form': form})

templates/layout.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">
    <title>{% block title %} {% endblock %} - School of Net</title>
    <link rel="icon" href="{% static 'img/icone.png' %}">
    <link rel="stylesheet" href="{% static 'css/sticky-footer.css' %}">
</head>
<body>
<h1>
    Django Intermediário {% if request.user.is_authenticated %} Olá, {{ request.user.get_full_name }} {% endif %}
</h1>
{% block content %}

{% endblock %}


<footer class="footer">
    <div class="container">
        <span class="text-muted">Administração de endereços dos usuários do site</span>
    </div>
</footer>

<!-- Scripts -->
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap4/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/my_app/address/create.html
{% extends "layout.html" %}

{% block title %}Novo endereço{% endblock %}

{% block content %}
    <div class="container">
        <h3>Novo endereço</h3>
        <form action="{% url 'my_app:address_create' %}" method="post" {% if form_submitted %}class="was-validated" {% endif %}>
            {% csrf_token %}
            {% include 'my_app/address/form_django.html' %}
            <button type="submit" class="btn btn-primary">Criar</button>
        </form>
    </div>
{% endblock %}

templates/my_app/address/destroy.html
{% extends "layout.html" %}

{% block title %}Excluir endereço{% endblock %}

{% block content %}
    <div class="container">
        <h3>Excluir endereço - {{ address.address }}</h3>
        <form action="{% url 'my_app:address_destroy' address.id %}" method="post">
            {% csrf_token %}
            <fieldset disabled>
                {% include 'my_app/address/form_django.html' %}
            </fieldset>
            <button type="submit" class="btn btn-danger">Excluir</button>
        </form>
    </div>
{% endblock %}

templates/my_app/address/form.html
{% csrf_token %}
<div class="form-group">
    <label for="address">Endereço</label>
    <input type="text" id="address" name="address" class="form-control" value="{{ address.address }}">
</div>
<div class="form-group">
    <label for="address_complement">Complemento</label>
    <input type="text" id="address_complement" name="address_complement" class="form-control"
           value="{{ address.address_complement_normalized }}">
</div>
<div class="form-group">
    <label for="city">Cidade</label>
    <input type="text" id="city" name="city" class="form-control" value="{{ address.city }}">
</div>
<div class="form-group">
    <label for="state">Estado</label>
    <select id="state" name="state" class="form-control">
        {% for state in states %}
            <option value="{{ state.0 }}"
                    {% if state.0 == address.state %}selected="selected"{% endif %}>{{ state.1 }}</option>
        {% endfor %}
    </select>
</div>
<div class="form-group">
    <label for="country">País</label>
    <input type="text" id="country" name="country" class="form-control" value="{{ address.country }}">
</div>

templates/my_app/address/form_django.html
<div class="form-group">
    {{ form.address.label_tag }}
    {{ form.address }}
    <div class="invalid-feedback">
        {{ form.address.errors }}
    </div>
</div>
<div class="form-group">
    {{ form.address_complement.label_tag }}
    {{ form.address_complement }}
    <div class="invalid-feedback">
        {{ form.address_complement.errors }}
    </div>
</div>
<div class="form-group">
    {{ form.city.label_tag }}
    {{ form.city }}
    <div class="invalid-feedback">
        {{ form.city.errors }}
    </div>
</div>
<div class="form-group">
    {{ form.state.label_tag }}
    {{ form.state }}
    <div class="invalid-feedback">
        {{ form.state.errors }}
    </div>
</div>
<div class="form-group">
    {{ form.country.label_tag }}
    {{ form.country }}
    <div class="invalid-feedback">
        {{ form.country.errors }}
    </div>
</div>

templates/my_app/address/list.html
{% extends "layout.html" %}

{% block title %}Listagem de endereços{% endblock %}

{% block content %}
    <div class="container">
        <h3>Listagem de endereços</h3>
        <a href="{% url 'my_app:address_create' %}" class="btn btn-primary">Novo endereço</a>
        <br/><br/>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Endereço</th>
                <th>Complemento</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            {% for address in addresses %}
                <tr>
                    <td>{{ address.id }}</td>
                    <td>{{ address.address }}</td>
                    <td>{{ address.address_complement_normalized }}</td>
                    <td>{{ address.city }}</td>
                    <td>{{ address.state }}</td>
                    <td>
                        <a href="{% url 'my_app:address_update' address.id %}">Editar<a> |
                            <a href="{% url 'my_app:address_destroy' address.id %}">Excluir<a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/my_app/address/update.html
{% extends "layout.html" %}

{% block title %}Editar endereço{% endblock %}

{% block content %}
    <div class="container">
        <h3>Editar endereço - {{ address.address }}</h3>
        <form action="{% url 'my_app:address_update' address.id %}" method="post" {% if form_submitted %}class="was-validated" {% endif %}>
            {% csrf_token %}
            {% include 'my_app/address/form_django.html' %}
            <button type="submit" class="btn btn-primary">Atualizar</button>
        </form>
    </div>
{% endblock %}

templates/my_app/home.html
{% extends 'layout.html' %}

{% block title %} Home {% endblock %}

{% block content %}

    <div class="container">
        <h3>Estou autenticado</h3>
        <a href="/logout/">Logout</a>
    </div>

{% endblock %}

templates/my_app/login.html
{% extends 'layout.html' %}

{% block title %} Login de usuário {% endblock %}

{% block content %}

    <div class="container">
        <h3>Login de usuário</h3>
        {% if message %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">E-mail</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="Entre com o e-mail">
            </div>
            <div class="form-group">
                <label for="password">Senha</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="Entre com a senha">
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
        </form>
    </div>

{% endblock %}